### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/psautohint#101]
I think it is time to cut a new stable release, @miguelsousa and @anthrotype any objections?

Given the nature of changes, I think it should be 1.8.0 not 1.7.1 as I originally planned.

**Comment by anthrotype** [comment]
sounds good to me.

**Comment by miguelsousa** [comment]
Sounds good to me too

**Comment by anthrotype** [comment]
Ah! Something just occurred to me.. since we now install a autohintexe console script, what if one installs afdko after psautohint? The latter’s “good” autohintexe launcher would be overwritten by the “bad” 32-bit only standalone executable. I think that if we want the two to coexist peacefully in the same site packages we need afdko to stop installing a autohintexe to bin/Scripts.

**Comment by anthrotype** [comment]
Similarly uninstalling afdko would remove the autohintexe launcher installed by psautohint..

**Comment by khaledhosny** [comment]
Right, so I guess we need AFDKO to drop its autohintexe first, cut a new stable release (after whatever number of beta releases until we are confident enough, of course), then we immediately cut one (so that people installing AFDKO would still get a working autohint), right?

**Comment by khaledhosny** [comment]
Alternatively, we can drop the wrapper (not a fan of it anyway), and AFDKO’s autohint could be adapted to look for the binary in the right place not in the PATH. That would be the cleaner solution I think.

**Comment by anthrotype** [comment]
I like the second option

**Comment by khaledhosny** [comment]
I just made a new stable release.
