### ISSUE TITLE
Import problem with _psautohint in python zipapp

### ISSUE THREAD

**Issue by kontur** [adobe-type-tools/psautohint#166]
Hey,

I'm packaging up a CLI tool as python zipapp which includes psautohint. The script runs fine when executed normally, but when I run the zipapp I get an import error from psautohint:

```
ERROR: Cannot import module 'foobar.barfoo ImportError 'cannot import name '_psautohint' from 'psautohint' (/Users/johannes/foobar.pyz/psautohint/__init__.py)'.
…
File "/Users/johannes/foobar.pyz/afdko/ufotools.py", line 19, in <module>
    from psautohint.ufoFont import UFOFontData as psautohintUFOFontData
  File "/Users/johannes/foobar.pyz/psautohint/__init__.py", line 9, in <module>
    from . import _psautohint
ImportError: cannot import name '_psautohint' from 'psautohint' (/Users/johannes/foobar.pyz/psautohint/__init__.py)
```

Looking at the [line  in question](https://github.com/adobe-type-tools/psautohint/blob/master/python/psautohint/__init__.py#L9) I don’t quite follow how this import is supposed to work — there is no such module in the directory, but only `_psautohint.c`? Is the difference from my installed module run as python script to the zipapp package that psautohint does something to generate or interpret a python module from that `c` file which it can then import — but does not do this for the zipapp?

The code for making the zipapp looks like this, so psautohint is installed via pip there before being packaged:

```
python3 -m pip install -r requirements.txt --target tmp --upgrade
python3 -m zipapp tmp/foobar -m "cli_command:cli_command" -p "/usr/bin/env python3"
```

Am I missing something obvious or how does that import work, and why is it failing? :)

**Comment by anthrotype** [comment]
I recommend you to use tools like https://github.com/linkedin/shiv to produce a self-contained python zip app instead of running the zipapp module yourself. It takes care of all edge cases, including the one you fell into here.
I use the same approach in fontmake, see
https://github.com/googlefonts/fontmake/blob/master/build_pyz.sh
https://github.com/googlefonts/fontmake/releases/tag/v1.9.3

**Comment by anthrotype** [comment]
> Am I missing something obvious

yep :)

So, the _psautohint.c is a C source file, that is compiled into a so-called extension module, named _psautohint.so on Unix or _psautohint.dll on Windows; this is like a shared library that is dynamically loaded and linked with the python executable as you do `import`. It's compiled, native binary file that only work for a specific platform and architecture, unlike the regular python modules (which are just text files interpreted at runtime, not native executables or libraries). The wheel package for psautohint contains this extension module so that when you do `pip install` the installer downloads and installs the correct package for your platform. You have to build the module using the native C/C++ compiler toolchain for your platform before you can import it from within python.

**Comment by anthrotype** [comment]
I closed this because it's not directly related to psautohint but is a more general issue as to how to package zipapps containing compiled modules.
@kontur feel free to contact me if you have more questions about shiv or similar.

**Comment by kontur** [comment]
Thanks for the pointers. If you don't mind my asking here so others might find the same information: How does shiv get around the problem with the precompiled C file? Doesn't it also just install (and trigger the native binary compilation) and then pack that up?

The tmp pip install I perform before the zipapp does trigger the install of psautohint and generates a `_psautohint.cpython-37m-darwin.so` (in my case) in the tmp packages folder — which is the same as my site-packages I run for running and successfully importing when running as module from a script. Is that .so file what gets imported as _psautohint when I call psautohint from my script, or does it get somehow compiled or transformed still on the fly?

Also, judging from your fontmake example this means the generated pyz of shiv is platform specific (which makes sense), but then couldn't I also simply copy that compiled version of the C file from my local install into the psautohint module to be imported when called in the pyz (if indeed it is something else still and the above .so file I am seeing anyway)?

**Comment by anthrotype** [comment]
I don't have the time to investigate why the import is failing when you manually create your zipapp, but bear in mind that the details of python import machinery are complicated and you're better off using an established tool than cooking up your own solution to this problem.

yes, it is platform specific. It can't be imported on a different machine with different operating system or architecture.

**Comment by kontur** [comment]
👍 yes, merely trying to understand what sets shiv apart from zipapp (which is also an established tool, I reckon ;) ). Testing with shiv now to see what that amounts to, thanks again for the pointer(s)!

**Comment by anthrotype** [comment]
feel free to look at shiv source code if you want to understand how it works. It actually bundles a slightly modified implementation of the stdlib zipapp.py module
https://github.com/linkedin/shiv/blob/master/src/shiv/builder.py

**Comment by anthrotype** [comment]
> zipapp (which is also an established tool, I reckon ;) )

sure, the principle is the same. But one thing is zipping-up a bunch of simple python modules in a folder with a `__main__.py`, another is bundling a more complex app with possibly compiled dependencies.

**Comment by anthrotype** [comment]
oh now I remember the reason why your solution doesn't work with compiled extension modules. The zipapp-generated script is imported and run directly from the zip file without extracting it to the filesystem first (it's a feature of python to be able to import from zip file). But... for dynamically loaded extensions, they need to be extracted first to be able to import them. That's what shiv does with its bundled bootstrap module. Also pyinstaller (which bundles python runtime itself) has to unzip the thing to make it work with native stuff. Yeah, you just can't with plain zipapp.

**Comment by anthrotype** [comment]
I am digressing (sorry Miguel for the spam) but this is exactly the reason why this module is not marked as `zip_safe`, i.e. it cannot be run directly from zipped .egg file (the legacy easy_install/setuptools distribution packages that preceded the current .whl wheels distribtion packges used with pip).
See https://github.com/adobe-type-tools/psautohint/blob/edc135b05875b1cd9a625693c72ab2b7eefbb05d/setup.py#L642

**Comment by kontur** [comment]
Ah yes, the bootstrapping part makes sense. It works via shiv, but gives me this warning (which I presume is a shiv error log, not psautohints’?):

```
/Users/johannes/.shiv/test_22611a8e-9c48-49f8-a7c0-a2c92d7da648/site-packages/psautohint/__init__.py:24: UserWarning: embedded 'autohintexe' executable not found: '/Users/johannes/.shiv/test_22611a8e-9c48-49f8-a7c0-a2c92d7da648/site-packages/psautohint/autohintexe'
  "embedded 'autohintexe' executable not found: %r" % AUTOHINTEXE
```

It does, however, autohint as it should, at least telling by logs and filesize. ✔️

**Comment by anthrotype** [comment]
that warning comes from within the psautohint module, I am not sure whether the autohintexe is essential or not.

**Comment by anthrotype** [comment]
hm actually, I tried making a shiv pyz app for psautohint and if I unzip the bundle I can see that the `autohintexe` file is there.

https://github.com/adobe-type-tools/psautohint/blob/edc135b05875b1cd9a625693c72ab2b7eefbb05d/python/psautohint/__init__.py#L17-L25

Ah! maybe the reason the check above is failing is because the check above is also asserting that the file is flagged as executable. Yeah, it looks like shiv unzips the package in a temporary location but loses the executable flag, hence `os.access(AUTOHINTEXE, os.X_OK)` returns false (which means it can't be executed as such by the shell, at least on posix).

Open an issue on shiv repository please, they'll figure out how to fix this. Tell them that a bundled native exectutable loses its execute permission flag after being unzipped by shiv bootstrapper.

**Comment by anthrotype** [comment]
yes, shiv simply calls extract method of ZipFile, thus it loses any previous exectutable permissions. It should instead do something similar to what the pip installer does when unpacking a wheel (which is also a zip file):
https://github.com/pypa/pip/blob/83d813c01e8debe7fd2bee4af106da06c915d3fc/src/pip/_internal/utils/misc.py#L523-L566

**Comment by anthrotype** [comment]
@kontur I'll open the issue, thanks.

**Comment by anthrotype** [comment]
oh ok, thanks :) I'll comment over there.

**Comment by kontur** [comment]
;) thanks a lot @anthrotype
