### ISSUE TITLE
Move glyph hash to individual glyphs lib?

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/psautohint#173]
I have been wondering since I started touching this part of the code why it is complicating things by maintaining the hashes in a separate file with its own undocumented syntax. Why not have a key in glyph lib that stores the hash?

If we want to do this, now is probably a good time to do it since we are doing many hash changes that is invalidating many glyphs anyway (or we could keep the code that reads the old hash file, but always save in the new glyph lib key). We will also need to change other AFDKO tools that make use of the hashes.

**Comment by khaledhosny** [comment]
cc @miguelsousa @frankrolf

**Comment by khaledhosny** [comment]
And also may be add the key to the UFO spec and document the algorithm, since other tools seem to be interested in glyph hashing. cc @jenskutilek

**Comment by miguelsousa** [comment]
I like the idea. Go ahead.

**Comment by frankrolf** [comment]
Would it still possible to exclude hashes from a repo then?

**Comment by miguelsousa** [comment]
@frankrolf I don't understand your question. What's your use case?

**Comment by frankrolf** [comment]
Maybe I’m not thinking the right thing here. My current workflow consists of using the hashed glyphs workflow for speed improvement, but not recording the hashes in got commits (because they produce a lot of noise).
For clarification, see my .gitignore file here:
https://github.com/adobe-fonts/source-serif-pro/blob/dev/.gitignore

**Comment by miguelsousa** [comment]
I think what Khaled is suggesting is something like this,

```xml
<?xml version='1.0' encoding='UTF-8'?>
<glyph name="a" format="2">
  <advance width="500"/>
  <outline>
    <contour>
      <point x="0" y="0" type="line"/>
      <point x="140" y="0" type="line"/>
      <point x="140" y="140" type="line"/>
      <point x="0" y="140" type="line"/>
    </contour>
  </outline>
  <lib>
    <dict>
      <key>public.hash</key>
      <string>w500l00l1400l140140l0140</string>
    </dict>
  </lib>
</glyph>
```

You won't be able to gitignore just the hash portion of the file.

**Comment by jenskutilek** [comment]
This would be added only to a processed layer (e.g. the autohinted layer), right? Adding the hash to the default layer would make no sense, because it would go out of sync, unless all editors would be required to update it on every outline operation.

**Comment by jenskutilek** [comment]
I guess what I was trying to say is that when the hash is stored in the glyph lib of the processed layer, it will also be excluded from the repository according to your .gitignore file, right @frankrolf?

**Comment by frankrolf** [comment]
I drafted a response to this before, but it wasn’t fully thought through.
I think what’s hashed is the state of the unprocessed glyph. Otherwise there’d be nothing to compare to. In addition to that, if a glyph doesn’t need processing (e.g. the space character), no processed glyph is stored, but a hash is still recorded to track changes.

There have been some confusions on my end about hashing in the past – see for example https://github.com/adobe-type-tools/afdko/issues/283

If the hash is attached to the .glif file, it’ll presumably only change if something else within is changing, so my problem may not be that significant after all.

**Comment by frankrolf** [comment]
Responding to this:
> Adding the hash to the default layer would make no sense, because it would go out of sync, unless all editors would be required to update it on every outline operation.

Yes, it would go out of sync, that’s the whole idea of the hash! :-)
If editors would update the hash, the relationship between foreground glyph and processed glyph would break – so it’s better if they leave it alone.

**Comment by jenskutilek** [comment]
Maybe I've got it backwards, and I haven't checked how your tools use the hash, but I figured the processed layer would keep the hash, saying "I belong to the default layer identified by this hash", so a tool that wants to check the processed layer is still valid would compute the hash for the default layer and see if the processed layer lib entry for the hash matches. If it does, the layer is still current; if it doesn't, it processing has to start from the default layer again.

**Comment by khaledhosny** [comment]
That is going to complicate things needlessly, lets just keep things as they are now.
