### ISSUE TITLE
Add arg flags compatible with afdko autohint

### ISSUE THREAD

**Issue by josh-hadley** [adobe-type-tools/psautohint#176]
Update `argparse` configuration in `psautohint` to accept the same single-hyphen flags as afdko's autohint program for the same flag meaning. For example, add `-xgf` for `--exclude-glyphs-file`.

**Comment by khaledhosny** [comment]
Breaking compatibility with `autohint` was intentional, see #28 and #43. I don’t think we can be fully compatible with `autohint` without changing current `psautohint` arg parsing in an incompatible way.

If full `authint` compatibility is required, then I suggest taking the existing `autohint.py`, striping everything except command line arg parsing and making it call `psautohint` module internally.

**Comment by josh-hadley** [comment]
Full `autohint` compatibility is not necessarily _required_, just desirable to aid in testing that `psautohint` yields the same results as `autohint` with the same (or equivalent) options. This is a step in phasing `autohint` out of the AFDKO in favor of `psautohint`. We want to reuse existing `autohint` test cases as much as possible and minimize re-writing the tests. Having `psautohint` use the same options/flags should make that process a lot easier.

Regarding the concern about `argparse`: @miguelsousa raised this with me directly as well. We developed some tests using Python 3 `argparse` and as a result of those I believe the concerns about `argparse` may be unfounded (they were possibly an issue with older Python, but moving forward we will only be supporting Python 3.6 in `psautohint` anyway -- see #175 -- so if it works with Python 3.6+ `argparse` then I think we are OK. Also if 100% compatibility proves impossible, that's also OK as this initiative is mainly to make compatibility testing a bit more efficient.

**Comment by khaledhosny** [comment]
As long as the existing `psauthint` is not changed in an incompatible way, I have no objection.
