### ISSUE TITLE
significant amount of code in VStemMiss() has no effect

### ISSUE THREAD

**Issue by cjchapman** [adobe-type-tools/psautohint#194]
These lines:

https://github.com/adobe-type-tools/psautohint/blob/7ac1e65feffd90948175a57a6e51a49a31c93262/libpsautohint/src/eval.c#L288-L293

and these lines:

https://github.com/adobe-type-tools/psautohint/blob/7ac1e65feffd90948175a57a6e51a49a31c93262/libpsautohint/src/eval.c#L296-L297

have no effect as `dist` is not used after that.

**Comment by readroberts** [comment]
Since I was as concerned that we lost useful code on VStemMiss() that did use these lines at some point, I tracked this back to the 1992 SunOS sources. I now recall that when PS hinting was developed, H hints were developed first, then V hint support added later. It is clear that VStemMiss() was copied from HStemMiss(), and then modified so that it does not reference 'dist', leaving some lines unneeded. This was an editing error, and these lines were never used.
