### ISSUE TITLE
Clarify what the "Uninitialized extra hints list" and "Failure in processing outline data" errors mean

### ISSUE THREAD

**Issue by kontur** [adobe-type-tools/psautohint#236]
From the same Glyphsapp font source I am extracting and compiling some 40+ fonts. Only one of them fails to autohint on one particular glyph with the error:

> ERROR: u0439:   Conflicts with current hints: 164 0 309 0 y.
ERROR: u0439:   Conflicts with current hints: 164 0 309 0 y.
ERROR: u0439:   Conflicts with current hints: 164 0 309 0 y.
ERROR: u0439:   Conflicts with current hints: 164 0 306 0 y.
ERROR: u0439: Uninitialized extra hints list.
ERROR: u0439: Failure in processing outline data.

This will actually crash the hinting process.

The "Conflicts with current hints" I already know is more of a debug information, but what do the others mean? It would be nice to not just skip that one glyph but understand the underlying problem.

**Comment by josh-hadley** [comment]
The "Failure in processing outline data" is a kind of catch-all, generated by the Python code when the underlying C code returns with an error. I think in this case, it's the "Uninitialized extra hints list" that is doing that.

Any chance of getting a copy of the font that causes this? Send privately if needed. It would be useful to have a test case to step through the code and identify the root cause, and help improve the messaging.

**Comment by skef** [comment]
FWIW these messages aren't present in the `pyport` branch and different handling of this part of the code means this issue won't be relevant anymore (which is not to guarantee there won't be other related problems ... )

**Comment by skef** [comment]
This should no longer be an issue in otfautohint (in afdko, soon to be released).
