### ISSUE TITLE
Codacy is misconfgured?

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/psautohint#50]
Opening https://app.codacy.com/project/adobe-type-tools/psautohint/dashboard, I see this message:

>  Hey Seems like we stopped receiving your coverage results. Check your CI server! 

And the latest changes/pull requests are not shown. However the pull requests seems to point to https://app.codacy.com/project/frankrolf/psautohint/dashboard, which suggests a misconfiguration somewhere.

**Comment by miguelsousa** [comment]
The lack of coverage results is expected, because of #36. Codecov provides a lot more insight into the coverage results across branches, commits and pulls, so there's really no need to use Codacy's coverage analysis feature.

The result of the PR is at https://app.codacy.com/app/adobe-type-tools/psautohint/pullRequest?prid=1850543 . Got that link from the review of #49.
I don't know where you got that other link from; Frank is not even a member of Codacy's adobe-type-tools organization account.

One thing that Codacy doesn't do by default is branch analysis; it has to be switched on for each branch, as you can see from the screenshot below. That page is at https://app.codacy.com/app/adobe-type-tools/psautohint/settings/branches . Let me know if you can't get to it.
<img width="1104" alt="branches" src="https://user-images.githubusercontent.com/2119742/42186314-0c8d7244-7e01-11e8-830b-8cb67a8a3953.png">

**Comment by khaledhosny** [comment]
No idea how I got that link from either, I don’t get it anymore. But if everything is working as intended, then sorry for the noise.

**Comment by khaledhosny** [comment]
I think I found where I got that link, look at the list of checks at the end of #49, and check the “Codacy/PR Quality Review” link, here I get https://app.codacy.com/app/frankrolf/psautohint/pullRequest?prid=1850424.

**Comment by khaledhosny** [comment]
![image](https://user-images.githubusercontent.com/93914/42191113-52e84d94-7e61-11e8-95d6-84c9a7cb427a.png)

(See the link shown in the status bar).

**Comment by miguelsousa** [comment]
strange. For me that same link points to https://app.codacy.com/app/adobe-type-tools/psautohint/pullRequest?prid=1850543
Going to logout from GH and see what I get.

**Comment by miguelsousa** [comment]
oh, I just saw it without logging out. Let me check the repository's webhooks

**Comment by miguelsousa** [comment]
Not sure what's going on. @frankrolf may need to do something on his account.
In the meantime, this is the gateway page to the PR analysis https://app.codacy.com/app/adobe-type-tools/psautohint/pullRequests?bid=6534457

Please leave this open until we sort things out.

**Comment by miguelsousa** [comment]
this should be fixed now

**Comment by khaledhosny** [comment]
Codacy seems to be completely gone from PRs now.

**Comment by miguelsousa** [comment]
@khaledhosny Does it not show on #62 for you? I can see it.

**Comment by khaledhosny** [comment]
It shows now, not an hour ago :)

**Comment by miguelsousa** [comment]
Sometimes it takes a bit to show up. I've seen it happen on PRs from other repos.
